import type { ParallaxInput } from './ParallaxSystem';

export class MouseParallaxAdapter {
  private x = 0;
  private y = 0;
  private targetX = 0;
  private targetY = 0;

  constructor(private readonly target: Window = window) {
    if (typeof this.target !== 'undefined' && this.target.addEventListener) {
      this.target.addEventListener('mousemove', this.onMove);
    }
  }

  private onMove = (e: MouseEvent) => {
    // Ignore synthetic mouse events generated by mobile touch taps
    const caps = (e as unknown as { sourceCapabilities?: { firesTouchEvents?: boolean } }).sourceCapabilities;
    if (caps && caps.firesTouchEvents) {
      return;
    }
    const w = (this.target && this.target.innerWidth) || 1;
    const h = (this.target && this.target.innerHeight) || 1;
    this.targetX = (e.clientX / w) * 2 - 1; // [-1, 1]
    this.targetY = (e.clientY / h) * 2 - 1;
  };

  getInput(): ParallaxInput {
    this.x += (this.targetX - this.x) * 0.15;
    this.y += (this.targetY - this.y) * 0.15;
    return { x: this.x, y: this.y };
  }

  destroy(): void {
    if (typeof this.target !== 'undefined' && this.target.removeEventListener) {
      this.target.removeEventListener('mousemove', this.onMove);
    }
  }
}
