import type { SceneConfig } from './scene';
import { sceneAssets } from './assets';

/**
 * The static scene configuration. Authoritative source: docs/scene-spec.md.
 */
export const sceneData: SceneConfig = {
  masterWidth: 1920,
  masterHeight: 1080,
  objects: [
    {
      id: 'sky',
      asset: sceneAssets.sky,
      x: 0,
      y: -275,
      width: 1920,
      height: 1080,
      depth: 0.0,
      layerOrder: 0,
    },
    {
      id: 'sun',
      asset: sceneAssets.sun,
      x: 950.2,
      y: 429.5,
      width: 140,
      height: 100,
      depth: 0.25,
      layerOrder: 1,
    },
    {
      id: 'mountains',
      asset: sceneAssets.mountains,
      x: 0,
      y: 279,
      width: 1920,
      height: 324,
      depth: -0.1,
      layerOrder: 2,
    },
    {
      id: 'city',
      asset: sceneAssets.city,
      x: 0,
      y: 270.5,
      width: 1920,
      height: 667,
      depth: 0.75,
      layerOrder: 3,
    },
    {
      id: 'midTrees',
      asset: sceneAssets.midTrees,
      x: 0,
      y: 38.5,
      width: 1920,
      height: 1031,
      depth: 1.0,
      layerOrder: 4,
    },
    {
      id: 'ground',
      asset: sceneAssets.ground,
      x: 0,
      y: 770,
      width: 1920,
      height: 322,
      depth: 1.95,
      layerOrder: 5,
    },
    {
      id: 'bench',
      asset: sceneAssets.bench,
      x: 656.2,
      y: 730.2,
      width: 634,
      height: 305,
      depth: 1.95, // Locked to ground depth so the bench is firmly planted
      layerOrder: 6,
    },
    {
      id: 'signRight',
      asset: sceneAssets.signRight,
      x: 1347.4,
      y: 501.2,
      width: 240,
      height: 400,
      depth: 1.8,
      layerOrder: 7,
      interactive: true,
    },
    {
      id: 'screenLeft',
      asset: sceneAssets.screenLeft,
      x: 345.3,
      y: 838.7,
      width: 224,
      height: 180,
      depth: 1.85,
      layerOrder: 8,
      interactive: true,
    },
    {
      id: 'screenRight',
      asset: sceneAssets.screenRight,
      x: 1376.9,
      y: 840.7,
      width: 300,
      height: 200,
      depth: 1.85,
      layerOrder: 9,
      interactive: true,
    },
    {
      id: 'rightLamp',
      asset: sceneAssets.rightLamp,
      x: 1453.9,
      y: 540.7,
      width: 341,
      height: 511,
      depth: 1.8,
      layerOrder: 10,
    },
    {
      id: 'rightTree',
      asset: sceneAssets.rightTree,
      x: -15,
      y: -1,
      width: 749,
      height: 1081,
      depth: 2.0,
      layerOrder: 11,
    },
  ],
};
